// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACq5hf4TzKJv_hiKJUGmWybSOH6X3VLGs',
    appId: '1:52383721176:web:49c8011746d68ecd0e59ad',
    messagingSenderId: '52383721176',
    projectId: 'attention-bias-new',
    authDomain: 'attention-bias-new.firebaseapp.com',
    databaseURL: 'https://attention-bias-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attention-bias-new.appspot.com',
    measurementId: 'G-2PT0DBS5F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTfOpyGFuaTscfCat6lhtM-3uENkmwfvY',
    appId: '1:52383721176:android:6dae3d7ff45ab8990e59ad',
    messagingSenderId: '52383721176',
    projectId: 'attention-bias-new',
    databaseURL: 'https://attention-bias-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attention-bias-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCblnpcTOR7fQ2xyGPxh-LMN8hzVNE1spc',
    appId: '1:52383721176:ios:4f8ddb544ed7bc2b0e59ad',
    messagingSenderId: '52383721176',
    projectId: 'attention-bias-new',
    databaseURL: 'https://attention-bias-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attention-bias-new.appspot.com',
    androidClientId: '52383721176-77jk6lbptngir37eivug5blgsppflhqk.apps.googleusercontent.com',
    iosClientId: '52383721176-f04glule22hjtoq6eftblbvoqla75f9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.attentionBias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCblnpcTOR7fQ2xyGPxh-LMN8hzVNE1spc',
    appId: '1:52383721176:ios:4f8ddb544ed7bc2b0e59ad',
    messagingSenderId: '52383721176',
    projectId: 'attention-bias-new',
    databaseURL: 'https://attention-bias-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attention-bias-new.appspot.com',
    androidClientId: '52383721176-77jk6lbptngir37eivug5blgsppflhqk.apps.googleusercontent.com',
    iosClientId: '52383721176-f04glule22hjtoq6eftblbvoqla75f9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.attentionBias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACq5hf4TzKJv_hiKJUGmWybSOH6X3VLGs',
    appId: '1:52383721176:web:891ef3e3b299b6290e59ad',
    messagingSenderId: '52383721176',
    projectId: 'attention-bias-new',
    authDomain: 'attention-bias-new.firebaseapp.com',
    databaseURL: 'https://attention-bias-new-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'attention-bias-new.appspot.com',
    measurementId: 'G-3B8Z2ESP7F',
  );

}